apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment

spec:
  replicas: 5
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: client
          image: shivam123425/multi-worker
          ports:
            - containerPort: 3000